package com.mrm.ui;

import com.mrm.handler.TransactionHandler;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;

/**
 * Java class for displaying the Rental Machine UI Panel
 * @author RaghuNandan
 */
public class RentalMachineTopPanel extends javax.swing.JPanel {
    /**
     * Transaction Handler object
     */
    private TransactionHandler tHandlerObj;

    /**
     * Creates new form RentalMachineUI
     * @param status
     */
    public RentalMachineTopPanel(int status) {
        tHandlerObj = new TransactionHandler();
        initComponents();
        
        printReceiptButton.setEnabled(false);
        dispenseButton.setEnabled(false);
        
        if(status==1){
            machineStatusToggleButton.setBackground(Color.GREEN);
        }else{
            machineStatusToggleButton.setBackground(Color.RED);
            validateButton.setEnabled(false);
            ccNumberField.setEnabled(false);
            zipCodeField.setEnabled(false);
        }
        
        WindowListener exitListener = new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
               tHandlerObj.performResourceCleanUp();
            }
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        machineStatusToggleButton = new javax.swing.JToggleButton();
        machineStatus = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        ccNumberField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        zipCodeField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        validateButton = new javax.swing.JButton();
        printReceiptButton = new javax.swing.JButton();
        dispenseButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        machineStatusToggleButton.setText("ON/OFF");
        machineStatusToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                machineStatusToggleButtonActionPerformed(evt);
            }
        });

        machineStatus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        machineStatus.setText("Movie Rental Machine");

        ccNumberField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel1.setText("CREDITCARD NUMBER * :");

        zipCodeField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel2.setText("ENTER ZIP CODE *  : ");

        validateButton.setText("Validate");
        validateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validateButtonActionPerformed(evt);
            }
        });

        printReceiptButton.setText("Print Receipt");

        dispenseButton.setText("Dispense");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(machineStatus)
                        .addGap(76, 76, 76)
                        .addComponent(machineStatusToggleButton)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dispenseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(printReceiptButton, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(13, 13, 13))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ccNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(zipCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(validateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(machineStatusToggleButton)
                    .addComponent(machineStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(365, 365, 365)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ccNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dispenseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(zipCodeField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(validateButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(printReceiptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void machineStatusToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_machineStatusToggleButtonActionPerformed
        JPanel panel = new JPanel();
        JLabel label = new JLabel("Enter a password:");
        JPasswordField pass = new JPasswordField(10);
        panel.add(label);
        panel.add(pass);
        String[] options = new String[]{"LOGIN", "CANCEL"};
        int option = JOptionPane.showOptionDialog(null, panel, "Operator Login",
                                 JOptionPane.NO_OPTION, JOptionPane.PLAIN_MESSAGE,
                                 null, options, options[1]);
        if(option == 0) // pressing OK button
        {
            char[] password = pass.getPassword();
            String pwd = new String(password);
            System.out.println("Your password is: " + new String(password));
            if(pwd.equals("raghu")){
                
                new OperatorUI();
            }else{
                JOptionPane.showMessageDialog(panel, "Invalid Password");
            }
        }
    }//GEN-LAST:event_machineStatusToggleButtonActionPerformed

    private void validateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validateButtonActionPerformed
        Long cardNumber=null;
        Integer zipCode=null;
        if(ccNumberField.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please Enter a valid card number");
            ccNumberField.setText("");
            ccNumberField.setFocusable(true);
        }else if(zipCodeField.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please Enter a valid zip code");
            zipCodeField.setText("");
            zipCodeField.setFocusable(true);
        }else{
            try {
                cardNumber=Long.parseLong(ccNumberField.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Please Enter a valid Numerical Input");
                ccNumberField.setText("");
                ccNumberField.setFocusable(true);
            }
            if(cardNumber != null){
                try {
                    zipCode=Integer.parseInt(zipCodeField.getText());
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Please Enter a valid zip Input");
                     zipCodeField.setText("");
                     zipCodeField.setFocusable(true);
                }
            }
            if(zipCode != null && cardNumber != null){
                if(tHandlerObj.authenticateLogin(cardNumber, zipCode)){
                    zipCodeField.setEditable(false);
                    ccNumberField.setEditable(false);
                }else{
                    JOptionPane.showMessageDialog(this, "Invalid Credit card information, Please Re-enter");
                    zipCodeField.setText("");
                    ccNumberField.setText("");
                    ccNumberField.setFocusable(true);
                }
            }
        }
        
    }//GEN-LAST:event_validateButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ccNumberField;
    private javax.swing.JButton dispenseButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel machineStatus;
    private javax.swing.JToggleButton machineStatusToggleButton;
    private javax.swing.JButton printReceiptButton;
    private javax.swing.JButton validateButton;
    private javax.swing.JTextField zipCodeField;
    // End of variables declaration//GEN-END:variables
}
